{
 "title": "FritzBox",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Physical Link Layer Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "fritzbox_wan_layer1_link_status"
    }
   ]
  },
  {
   "title": "Downstream Max Bitrate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "Kbits",
   "valueName": "avg",
   "targets": [
    {
     "expr": "fritzbox_wan_layer1_downstream_max_bitrate"
    }
   ]
  },
  {
   "title": "Upstream Max Bitrate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "Kbits",
   "valueName": "avg",
   "targets": [
    {
     "expr": "fritzbox_wan_layer1_upstream_max_bitrate"
    }
   ]
  },
  {
   "title": "Current Traffic (bytes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(fritzbox_wan_bytes_received[5m])",
     "legendFormat": "download"
    },
    {
     "expr": "rate(fritzbox_wan_bytes_sent[5m])",
     "legendFormat": "upload"
    }
   ]
  },
  {
   "title": "Current Traffic (packets)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(fritzbox_wan_packets_received[5m])",
     "legendFormat": "download"
    },
    {
     "expr": "rate(fritzbox_wan_packets_sent[5m])",
     "legendFormat": "upload"
    }
   ]
  }
 ]
}